RUN_MODE_PLAN: 1 # 1 - 징검다리, 2 외나무다리, 3 - 장애물

SUPPORT_HEIGHT: 0.30

ss_SUPPORT_BIAS: 0.05 
ss_SUPPORT_xMAX: 0.32
ss_SUPPORT_xMIN: 0.15
ss_SUPPORT_yMAX: 0.40
ss_SUPPORT_yMIN: 0.2

np_SUPPORT_BIAS: 0.02
np_SUPPORT_xMAX: 0.25
np_SUPPORT_xMIN: 0.25
np_SUPPORT_yMAX: 0.35
np_SUPPORT_yMIN: 0.10
